app_package/bp_main/routes.py
from flask import Blueprint
from flask import render_template, current_app, send_from_directory, g, \
    request
import os
from app_package._common.utilities import custom_logger, wrap_up_session
from ws_utilities import create_df_from_db_table_name
from ws_models import DatabaseSession

logger_bp_main = custom_logger('bp_main.log')
bp_main = Blueprint('bp_main', __name__)

# @bp_main.before_request
# def before_request():

#     # Assign a new session to a global `g` object, accessible during the whole request
#     g.db_session = DatabaseSession()


#     if request.referrer:
#         logger_bp_main.info(f"- request.referrer: {request.referrer} ")
    
#     logger_bp_main.info(f"- db_session ID: {id(g.db_session)} ")
    
#     if request.endpoint:
#         logger_bp_main.info(f"- request.endpoint: {request.endpoint} ")

# @bp_main.after_request
# def after_request(response):
#     logger_bp_main.info(f"---- after_request --- ")
#     if hasattr(g, 'db_session'):
#         wrap_up_session(logger_bp_main, g.db_session)
#     return response

@bp_main.route("/", methods=["GET","POST"])
def home():
    logger_bp_main.info(f"-- in home page route --")
    # df_users = create_df_from_db_table_name('users')
    # logger_bp_main.info(df_users)

    return render_template('main/home.html')

@bp_main.route("/download_ios", methods=["GET","POST"])
def download_ios():
    logger_bp_main.info(f"-- in download_ios route --")
    # download_test_flight_link = "https://testflight.apple.com/join/ZXNq4c8s"
    # try:
    with open(os.path.join(current_app.config.get('WEBSITE_FILES'),'TestFlightUrl.txt'), 'r') as file:
        download_test_flight_link = file.read().strip()  # .strip() removes any leading/trailing whitespace
    
    # except:
    #     download_test_flight_link="https://testflight.apple.com/join/LHzvgt5g"

    return render_template('main/download_ios.html', download_test_flight_link=download_test_flight_link)

@bp_main.route("/about", methods=["GET","POST"])
def about():
    logger_bp_main.info(f"-- in about page route --")

    test_flight_link = ""

    try:
        with open(os.path.join(current_app.config.get('WEBSITE_FILES'),'TestFlightUrl.txt'), 'r') as file:
            test_flight_link = file.read().strip()  # .strip() removes any leading/trailing whitespace
    except FileNotFoundError:
        logger_bp_main.info(f"- no TestFlight Link found")

    return render_template('main/about.html', test_flight_link=test_flight_link)

@bp_main.route('/privacy', methods = ['GET', 'POST'])
def privacy():
    logger_bp_main.info(f"-- in privacy page route --")
    return render_template('main/privacy.html')

@bp_main.route('/user_csv_documentation', methods = ['GET', 'POST'])
def user_csv_documentation():
    logger_bp_main.info(f"-- in user_csv_documentation route --")
    return render_template('main/user_csv_documentation.html')

@bp_main.route('/what_sticks_video/<filename>', methods = ['GET', 'POST'])
def what_sticks_video(filename):
    logger_bp_main.info(f"-- in what_sticks_video route --")

    if filename == "SleepTime20240130_shortDrawings.mp4":
        filename = "SleepTime_v03.mp4"

    return render_template('main/video_page.html', filename=filename)

# Website Files static data
@bp_main.route('/website_images/<filename>')
def website_images(filename):
    print("-- entered website_images -")
    print(f"Path to image file: {current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES')}")
    print(f"image filename: {filename}")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'), filename)

# Website Videos static data
@bp_main.route('/website_videos/<filename>')
def website_videos(filename):
    print("-- entered website_videos -")
    print(f"Path to image file: {current_app.config.get('DIR_WEBSITE_VIDEOS')}")
    print(f"image filename: {filename}")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_VIDEOS'), filename)

@bp_main.route('/website_images_favicon/<filename>')
def website_images_favicon(filename):
    print("-- entered website_images -")
    print(f"Path to image file: {os.path.join(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),'Favicon')}")
    print(f"image filename: {filename}")
    return send_from_directory(os.path.join(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),"Favicon"), filename)

@bp_main.route('/favicon_ico')
def favicon_ico():
    print("--- ** Favicon() ** ----")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),
                               'Favicon/favicon.ico', mimetype='image/vnd.microsoft.icon')

@bp_main.route('/robots.txt')
def robots_txt():
    # return send_from_directory(app.static_folder, 'robots.txt')
    return send_from_directory(current_app.config.get('WEBSITE_FILES'), 'robots.txt')

app_package/bp_users/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash, request, \
    abort, session, Response, current_app, send_from_directory, make_response, \
    send_file, jsonify, g
import bcrypt
from flask_login import login_required, login_user, logout_user, current_user
import os
import json
# from ws_models import sess, engine, text, Users
from ws_models import engine, DatabaseSession, text, Users
from app_package.bp_users.utils import  create_shortname_list, api_url, \
    send_reset_email
import datetime
import requests
import zipfile
from app_package._common.utilities import custom_logger, wrap_up_session
from ws_utilities import create_dashboard_table_object_json_file, \
    create_data_source_object_json_file


logger_bp_users = custom_logger('bp_users.log')
salt = bcrypt.gensalt()
bp_users = Blueprint('bp_users', __name__)


@bp_users.route('/login', methods = ['GET', 'POST'])
def login():
    logger_bp_users.info('- in login -')
    db_session = g.db_session
    if current_user.is_authenticated:
        return redirect(url_for('bp_users.user_home'))

    page_name = 'Login'
    
    if request.method == 'POST':
        # db_session = g.db_session
        formDict = request.form.to_dict()
        logger_bp_users.info(f"formDict: {formDict}")
        email = formDict.get('email')

        user = db_session.query(Users).filter_by(email=email).first()

        # verify password using hash
        password = formDict.get('password')

        if user:
            if password:
                if bcrypt.checkpw(password.encode(), user.password.encode()):
                    login_user(user)
                    
                    return redirect(url_for('bp_users.user_home'))
                else:
                    flash('Password or email incorrectly entered', 'warning')
            else:
                flash('Must enter password', 'warning')
        else:
            flash('No user by that name', 'warning')

    # wrap_up_session(logger_bp_users, db_session)
    return render_template('users/login.html', page_name = page_name)

@bp_users.route('/register', methods = ['GET', 'POST'])
def register():
    db_session = g.db_session
    if current_user.is_authenticated:
        return redirect(url_for('bp_main.user_home'))
    page_name = 'Register'

    if request.method == 'POST':
        formDict = request.form.to_dict()
        new_email = formDict.get('email')

        check_email = db_session.query(Users).filter_by(email = new_email).all()

        logger_bp_users.info(f"check_email: {check_email}")

        if len(check_email)==1:
            flash(f'The email you entered already exists you can sign in or try another email.', 'warning')
            return redirect(url_for('bp_users.register'))

        hash_pw = bcrypt.hashpw(formDict.get('password').encode(), salt)
        new_user = Users(email = new_email, password = hash_pw, timezone = "Etc/GMT")
        db_session.add(new_user)
        # sess.commit()

        # Send email confirming succesfull registration
        try:
            send_confirm_email(new_email)
        except:
            flash(f'Problem with email: {new_email}', 'warning')
            return redirect(url_for('bp_users.login'))

        #log user in
        print('--- new_user ---')
        print(new_user)
        login_user(new_user)
        flash(f'Succesfully registered: {new_email}', 'info')
        return redirect(url_for('bp_main.home'))
    wrap_up_session(logger_bp_users, db_session)
    return render_template('users/register.html', page_name = page_name)

@bp_users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('bp_main.home'))

@bp_users.route('/request_reset_password', methods = ["GET", "POST"])
def request_reset_password():
    logger_bp_users.info(f'- in request_reset_password')
    db_session = g.db_session
    page_name = 'Request Password Change'
    if current_user.is_authenticated:
        return redirect(url_for('bp_main.home'))
    # form = RequestResetForm()
    # if form.validate_on_submit():
    if request.method == 'POST':
        formDict = request.form.to_dict()
        email = formDict.get('email')
        user = db_session.query(Users).filter_by(email=email).first()
        if user:
            send_reset_email(user)
            # # logger_bp_users.info('Email reaquested to reset: ', email)
            # # send_reset_email(user)
            # base_url = api_url()
            # # reset_pass_token_payload = {"email":email}
            # reset_pass_token_payload = {
            #     "email":"nrodrig1@gmail.com",
            #     "ws_api_password":current_app.config.get('WS_API_PASSWORD')
            #     }
            # response_reset_pass_token = requests.request(
            #     'GET',base_url + '/get_reset_password_token', json=reset_pass_token_payload)
            # response_reset_pass_token.status_code

            # flash('Email has been sent with instructions to reset your password','info')
            # # return redirect(url_for('bp_users.login'))
        else:
            flash('Email has not been registered with What Sticks','warning')

        # return redirect(url_for('bp_users.reset_password'))
        return redirect(url_for('bp_users.request_reset_password'))
    return render_template('users/reset_request.html', page_name = page_name)

@bp_users.route('/reset_password', methods = ["GET", "POST"])
def reset_password():
    logger_bp_users.info(f"- accessed: reset_password with token")
    db_session = g.db_session
    # if current_user.is_authenticated:
    #     return redirect(url_for('bp_main.user_home'))
    token = request.args.get('token')
    user = Users.verify_reset_token(token)
    logger_bp_users.info(f'user:: {user}')
    
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('bp_users.reset_password'))
    if request.method == 'POST':
        logger_bp_users.info(f'request.method == POST')

        formDict = request.form.to_dict()
        logger_bp_users.info(f'formDict : {formDict}')

        new_user_obj = db_session.get(Users,user.id)
        hash_pw = bcrypt.hashpw(formDict.get('password_text').encode(), salt)
        new_user_obj.password = hash_pw
        # wrap_up_session(db_session, logger_bp_users)
        try:
            # perform some database operations
            db_session.commit()
            logger_bp_users.info("- perfomed: sess.commit() -")
        except Exception as e:
            db_session.rollback()  # Roll back the transaction on error
            logger_bp_users.info("- perfomed: sess.rollback() -")
            logger_bp_users.info(f"{type(e).__name__}: {e}")
            raise
        finally:
            db_session.close()  # Ensure the session is closed in any case
            logger_bp_users.info("- perfomed: sess.close() -")



        # base_url = api_url()
    
        # reset_pass_payload = {"password_text":formDict.get('password_text')}
        # headers = {'Content-Type':'application/json','x-access-token':token}
        # response_reset_pass = requests.request('POST',base_url + '/reset_password',headers=headers, json=reset_pass_payload)
        # response_reset_pass.status_code

        # if response_reset_pass.status_code == 200:
        #     logger_bp_users.info(f'Refresh database here')
        #     # # NOTE: I think this i unnecessary with the new db_session, before and teardown_appcontext implementation
        #     # # Expire session so new data will take into effect when user logs in again
        #     # sess.expire_all()
        #     # sess.commit()
        #     logout_user()
        #     return redirect(url_for('bp_users.login'))
        return redirect(url_for('bp_users.login'))
        # logger_bp_users.info(f'response_reset_pass.status_code: {response_reset_pass.status_code}')
        # logger_bp_users.info(f"password_text: {formDict.get('password_text')}")


    return render_template('users/reset_request.html', token = token, page_name='Enter New Password')

@bp_users.route('/user_home', methods = ['GET', 'POST'])
@login_required
def user_home():
    logger_bp_users.info("- accessed user_home -")
    user_file_prefix = f"user_{current_user.id:04}_df"
    user_files_list = [ i for i in os.listdir(current_app.config.get('DAILY_CSV')) if user_file_prefix in i ]
    user_files_list_shortname = create_shortname_list(user_files_list, current_user.id)
    
    if request.method == 'POST':
        formDict = request.form.to_dict()
        logger_bp_users.info(f'formDict : {formDict}')

        if formDict.get("btn_download_files"):
            logger_bp_users.info(f'- Selected btn_download_files -')
            # Get the directory where the CSV files are stored
            csv_directory = current_app.config.get('DAILY_CSV')

            # Define the zip file name based on the current user's ID
            zip_file_name = f"user_{current_user.id:04}_files.zip"
            zip_file_path = os.path.join(csv_directory, zip_file_name)

            # Create a zip file in write mode
            with zipfile.ZipFile(zip_file_path, 'w') as zipf:
                # Loop through each file in the directory
                for folder_name, subfolders, filenames in os.walk(csv_directory):
                    for filename in filenames:
                        # Check if the current file is in the user's file list
                        if filename in user_files_list:
                            # Create the full path to the file
                            file_path = os.path.join(folder_name, filename)
                            # Add the file to the zip archive
                            zipf.write(file_path, os.path.relpath(file_path, csv_directory))
        
            # After zipping, send the file to the client
            return send_file(zip_file_path, as_attachment=True)

        elif formDict.get("btn_recalculate_dashboard"):

app_package/templates/_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <script src="https://kit.fontawesome.com/dd4fc26679.js" crossorigin="anonymous"></script>
  
  <!-- Added bootstrap -->
  <link rel="stylesheet" href="../static/additional_styling/bootstrap-5.3.2-dist/css/bootstrap.min.css">
  <!-- colors for data tables are in bootstrap.min.css -->
  <script src="../static/additional_styling/bootstrap-5.3.2-dist/js/bootstrap.min.js"></script>

  <!-- Data tables -->
  <script src="../static/additional_styling/DataTables/jQuery-3.7.0/jquery-3.7.0.min.js"></script>
  <link rel="stylesheet" type="text/css" href="../static/additional_styling/DataTables/datatables.min.css"/>
  <script type="text/javascript" src="../static/additional_styling/DataTables/datatables.min.js"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <!-- <link rel="icon" href=" url_for('bp_main.website_files', filename='logo02_whiteBck.svg') " type="image/x-icon"> -->

  <!-- LinkedIn Links -->
  <meta name="theme-color" content="#000000">
  <meta 
  property="og:title"
  content="What Sticks"
/><meta 
  name="image"
  property="og:image"
  content="{{ url_for('bp_main.website_images_favicon', filename='linkedIn-1200x627.png') }}"
/><meta 
  name="author"
  content="What Sticks"
/><meta 
  property="og:description"
  content="The application that personalizes wellness."
/><meta 
  property="og:url"
  content="https://what-sticks.com"
/>
  <!-- icon for iPhone  shortcut -->
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('bp_main.website_images_favicon', filename='apple-icon-180x180.png') }}">
  <!-- favicon - image on tabs of browser pages-->
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('bp_main.website_images_favicon', filename='favicon-32x32.png') }}">

  <title>What Sticks</title>
</head>

<body>
  <div id="navbar_top" class="navbar_top" >
    <div class="div_hamburger">
      <button id="hamburger"  onclick="toggleMenu()"><i class="fas fa-bars" id="btn"></i></button>
    </div>
  </div><!-- navbar_top -->

  <!-- Slides out on small screen -->
  <div id="navbar_side" class="navbar_side navbar_side_hidden">
    <div class="div_close">
      <button class="btn_close" onclick="toggleMenu()"><i class="fa-solid fa-xmark"></i></button>
    </div>
    <div class="div_logo">
      <a href="{{ url_for('bp_main.home') }}">
        <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}"/>
      </a>
    </div>
    <div class="navbar_list">
      <ul>

        <li><a href="{{ url_for('bp_main.about') }}"><i class="fa-regular fa-address-card"></i>About</a></li>
        <li><a href="https://apps.apple.com/us/app/what-sticks-12/id6498888495"><i class="fa-solid fa-download"></i>Download iOS</a></li>
        <li><a href="{{ url_for('bp_main.privacy') }}"><i class="fa-solid fa-lock"></i>Privacy</a></li>

        {% if current_user.is_authenticated %}  
        <li><a href="{{ url_for('bp_users.user_home') }}"><i class="fa-solid fa-house"></i><span >User Home</span></a></li>
        {% if current_user.admin_permission %}  
        <li class="li_logged_in"><a href="{{ url_for('bp_admin.admin_page') }}"><i class="fa-solid fa-ghost"></i><span >Admin</span></a></li>  
        {% endif %}
        <li class="li_logged_in"><a href="{{ url_for('bp_users.logout') }}"><i class="fa-solid fa-right-to-bracket"></i>Logout</a></li>
        {% else %}
        <li><a href="{{ url_for('bp_users.login') }}"><i class="fa-solid fa-right-to-bracket"></i>Login</a></li>
        {% endif %}  
        
      </ul>

    </div>
  </div>

  <!-- Overlay -->
  <div id="overlay" onclick="toggleMenu()"></div>

  
  <div class="div_fixed_nav_and_main">


    <div class="flash_and_main">
      <div class="flash_custom_parent">

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
    
        <div class="alert alert-{{ category }} alert_custom keep_line_break" id="div_flash">
          <i class="close icon"></i>
    
          {{ message }}
          <div class="close_right">
            <input type="button" value=&#10006 onclick="removeFlash()" class=" btn_custom02">
          </div>
    
        </div>
        {% endfor %}<!-- for category, message in messages -->
        {% endif %}<!-- if messages -->
        {% endwith %}<!-- with messages = get_flashed_messages(with_categories=true) -->
    
      </div>
  
  
      {% block main %}{% endblock %}
    </div><!-- flash_and_main -->

    <!-- Big Screen Navbar-->
    <div  class="navbar_side navbar_side_wide">
      <div class="div_logo">
        <a href="{{ url_for('bp_main.home') }}">
          <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}"/>
        </a>
      </div>
      <div class="navbar_list">
        <ul>
          <li><a href="{{ url_for('bp_main.about') }}"><i class="fa-regular fa-address-card"></i>About</a></li>
          <li><a href="https://apps.apple.com/us/app/what-sticks-12/id6498888495"><i class="fa-solid fa-download"></i>Download iOS</a></li>
          <li><a href="{{ url_for('bp_main.privacy') }}"><i class="fa-solid fa-lock"></i>Privacy</a></li>

          {% if current_user.is_authenticated %}  
          <li><a href="{{ url_for('bp_users.user_home') }}"><i class="fa-solid fa-house"></i><span >User Home</span></a></li>
          {% if current_user.admin_permission %}  
          <li class="li_logged_in"><a href="{{ url_for('bp_admin.admin_page') }}"><i class="fa-solid fa-ghost"></i><span >Admin</span></a></li>  
          {% endif %}
          <li class="li_logged_in"><a href="{{ url_for('bp_users.logout') }}"><i class="fa-solid fa-right-to-bracket"></i>Logout</a></li>
          {% else %}
          <li><a href="{{ url_for('bp_users.login') }}"><i class="fa-solid fa-right-to-bracket"></i>Login</a></li>
          {% endif %}  
        </ul>
  
      </div><!-- navbar_list -->
    </div><!-- navbar_side navbar_side_wide -->


  </div><!-- div_fixed_nav_and_main-->

  

  <script>
    function toggleMenu() {
      const menu = document.getElementById('navbar_side');
      const overlay = document.getElementById('overlay');

      menu.classList.toggle('navbar_side_visible');
      overlay.classList.toggle('visible');
    }
</script>

  <!-- Remove flash on click -->
  <script>
    function removeFlash() {
      const element = document.getElementById('div_flash');
      element.remove();
    }
  </script>
</body>
</html>