app_package/bp_main/routes.py
from flask import Blueprint
from flask import render_template, current_app, send_from_directory, g, \
    request
import os
from app_package._common.utilities import custom_logger, wrap_up_session
from ws_utilities import create_df_from_db_table_name
from ws_models import DatabaseSession

logger_bp_main = custom_logger('bp_main.log')
bp_main = Blueprint('bp_main', __name__)

# @bp_main.before_request
# def before_request():

#     # Assign a new session to a global `g` object, accessible during the whole request
#     g.db_session = DatabaseSession()


#     if request.referrer:
#         logger_bp_main.info(f"- request.referrer: {request.referrer} ")
    
#     logger_bp_main.info(f"- db_session ID: {id(g.db_session)} ")
    
#     if request.endpoint:
#         logger_bp_main.info(f"- request.endpoint: {request.endpoint} ")

# @bp_main.after_request
# def after_request(response):
#     logger_bp_main.info(f"---- after_request --- ")
#     if hasattr(g, 'db_session'):
#         wrap_up_session(logger_bp_main, g.db_session)
#     return response

@bp_main.route("/", methods=["GET","POST"])
def home():
    logger_bp_main.info(f"-- in home page route --")
    # df_users = create_df_from_db_table_name('users')
    # logger_bp_main.info(df_users)

    return render_template('main/home.html')

@bp_main.route("/download_ios", methods=["GET","POST"])
def download_ios():
    logger_bp_main.info(f"-- in download_ios route --")
    # download_test_flight_link = "https://testflight.apple.com/join/ZXNq4c8s"
    # try:
    with open(os.path.join(current_app.config.get('WEBSITE_FILES'),'TestFlightUrl.txt'), 'r') as file:
        download_test_flight_link = file.read().strip()  # .strip() removes any leading/trailing whitespace
    
    # except:
    #     download_test_flight_link="https://testflight.apple.com/join/LHzvgt5g"

    return render_template('main/download_ios.html', download_test_flight_link=download_test_flight_link)

@bp_main.route("/about", methods=["GET","POST"])
def about():
    logger_bp_main.info(f"-- in about page route --")

    test_flight_link = ""

    try:
        with open(os.path.join(current_app.config.get('WEBSITE_FILES'),'TestFlightUrl.txt'), 'r') as file:
            test_flight_link = file.read().strip()  # .strip() removes any leading/trailing whitespace
    except FileNotFoundError:
        logger_bp_main.info(f"- no TestFlight Link found")

    return render_template('main/about.html', test_flight_link=test_flight_link)

@bp_main.route('/privacy', methods = ['GET', 'POST'])
def privacy():
    logger_bp_main.info(f"-- in privacy page route --")
    return render_template('main/privacy.html')

@bp_main.route('/user_csv_documentation', methods = ['GET', 'POST'])
def user_csv_documentation():
    logger_bp_main.info(f"-- in user_csv_documentation route --")
    return render_template('main/user_csv_documentation.html')

@bp_main.route('/what_sticks_video/<filename>', methods = ['GET', 'POST'])
def what_sticks_video(filename):
    logger_bp_main.info(f"-- in what_sticks_video route --")

    if filename == "SleepTime20240130_shortDrawings.mp4":
        filename = "SleepTime_v03.mp4"

    return render_template('main/video_page.html', filename=filename)

# Website Files static data
@bp_main.route('/website_images/<filename>')
def website_images(filename):
    print("-- entered website_images -")
    print(f"Path to image file: {current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES')}")
    print(f"image filename: {filename}")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'), filename)

# Website Videos static data
@bp_main.route('/website_videos/<filename>')
def website_videos(filename):
    print("-- entered website_videos -")
    print(f"Path to image file: {current_app.config.get('DIR_WEBSITE_VIDEOS')}")
    print(f"image filename: {filename}")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_VIDEOS'), filename)

@bp_main.route('/website_images_favicon/<filename>')
def website_images_favicon(filename):
    print("-- entered website_images -")
    print(f"Path to image file: {os.path.join(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),'Favicon')}")
    print(f"image filename: {filename}")
    return send_from_directory(os.path.join(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),"Favicon"), filename)

@bp_main.route('/favicon_ico')
def favicon_ico():
    print("--- ** Favicon() ** ----")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),
                               'Favicon/favicon.ico', mimetype='image/vnd.microsoft.icon')

@bp_main.route('/robots.txt')
def robots_txt():
    # return send_from_directory(app.static_folder, 'robots.txt')
    return send_from_directory(current_app.config.get('WEBSITE_FILES'), 'robots.txt')

app_package/templates/blog/create_post.html
{% extends "_layout.html" %}
{% block title %} Post to Blog {% endblock %}
{% block main %}
<form method="POST" id="form_create_post" enctype=multipart/form-data></form>

<div class="space_for_navbar_and_footer">

<div class="create_post_super">
  <div class="create_post">

    <h2>Upload/Create Blog Post</h2>

    <div class="a_div_right">
      <a href="{{ url_for('bp_blog.blog_user_home') }}" > Blog User Home </a>
    </div>
    <div class="create_post_framing">
      <div class="create_post_content">


        <label for="action">Step 1 Choose method:
          Upload zip that originated from
        </label>
        <select id="action" name="dropdown_upload_zip_type" onchange='onSelectChangeHandler()' form="form_create_post"
          name="origin_type">
          <!-- <option value="" selected disabled hidden>Choose here</option> -->
          <!-- <option value="zipped_html">Originate from word document</option>
          <option value="old_method_with_images">Origin from html</option> -->
          <option value="origin_from_word">MS Word document</option>
          <option value="origin_from_html">HTML document</option>
        </select>
        <br><br>


        <!-- new_method = origin_from_word -->
        <!-- <div id="new_method" class="new_method"> -->
        <div id="origin_from_word_id" class="origin_from_word_div">
          <div class="description_text_super">
            <div class="description_text">
              Zipped file with index.html <br>
              This process assumes you have started with a Word (.docx) file then converted to webpage(.filtered)
              in MS word. Then zipped the html and the .fld directory together.

              <!-- OLD 
              This upload assumes a compressed file is being submitted with the main page 'index.html'. There could be
              folder(s) with images. -->

              If you wish to embed another template you'll need to enter it manually with the double curly's include
              "template_name"
              close double curly's.
            </div><!--description_text-->

          </div><!-- description_text_super -->

          <div id="new_method_inputs">

            <div class="new_method_input_file">
              Step 2: Upload MS Word document saved as html:
              <!-- <input class="form-control" type="file" form="form_create_post" name="new_method" accept=".zip"
                placeholder=".html"> -->
              <input class="form-control" type="file" form="form_create_post" name="zip_file_origin_word" accept=".zip"
                placeholder=".html">

            </div><!-- blog_form_input_div -->
      <!-- 
            <div class="new_method_input_source_dropdown">
              <label for="action">Step 3: Where did index.html come from?</label>
              <select id="action" name="index_html_source" form="form_create_post" required>
                <option value="" selected disabled hidden>Choose here</option>
                <option value="ms_word">MS Word converted to html</option>
                <option value="original_html">Originally html</option>
              </select>
            </div><!-- new_method_input_source_dropdown 
        -->


          </div><!-- new_method_inputs -->

        </div><!-- new_method -->


        <!-- old_method = origin_from_html -->
        <div id="origin_from_html_id" class="origin_from_html_div">
          <h2> showing form for html upload</h2>
        </div>


        <div class="blog_form_bottom_buttons_and_progress">

          <div class="button_div_right">
            <input onclick="update()" type="submit" value="Upload" class="btn btn-primary btn_custom"
              form="form_create_post">
          </div>

          <div class="progress_div">
            Upload Progress Bar
            <div class="Progress_Status" id="Progress_Status">
              <div class="progress-bar progress-bar-striped" id="myprogressBar" role="progressbar"></div>
            </div><!-- Progress_Status -->
          </div><!-- progress_div -->

        </div><!-- blog_form_bottom_buttons_and_progress -->




      </div><!-- create_post_content (child of flex)-->
    </div><!-- create_post_framing (flex)-->

    <script>
      function onSelectChangeHandler() {
        console.log("-- action activaited?");
        var val = document.getElementById("action").value;
        console.log("user selected: " + val);

        switch (val) {
          // case "old_method_with_images":
          case "origin_from_word":
            document.getElementById("origin_from_word_id").style.display = "block";
            document.getElementById("origin_from_html_id").style.display = "none";
            // document.getElementById("delete").style.display = "none";
            console.log("Add word converted to html");
            break;

          // case "zipped_html":
          case "origin_from_html":
            document.getElementById("origin_from_word_id").style.display = "none";
            document.getElementById("origin_from_html_id").style.display = "block";
            // document.getElementById("delete").style.display = "none";
            console.log("Add html file");
            break;


        }
      }


    </script>

    <script>

      function update() {
        var element = document.getElementById("myprogressBar");
        var width = 10;
        var identity = setInterval(scene, 10);
        function scene() {
          if (width >= 100) {
            clearInterval(identity);
          } else {
            width++;
            element.style.width = width + '%';
          }
        }
      }
    </script>


  </div><!-- create_post (child of flex)-->
</div><!-- create_post_super (flex)-->

</div><!-- space_for_navbar_and_footer -->
{% endblock %}

app_package/templates/blog/edit_post.html
{% extends "_layout.html" %}
{% block title %} Post to Blog {% endblock %}
{% block main %}
<form method="POST" id="form_edit" enctype=multipart/form-data></form>

<div class="edit_post_super">

  <div class="blog_form_div">
    <div class="button_div_right">
      <a href="{{ url_for('bp_blog.blog_user_home') }}" > Blog User Home </a>
    </div>
    
    <h2>Edit blog post</h2>

    <div class="blog_form_sub_top">

      <div class="blog_form_label_div">
        <label for="blog_description">Title</label>
      </div>
      <div class="blog_form_input_div">
        <input type="text" class="form-control" name="blog_title" value="{{ title }}" form="form_edit">
      </div>

      <div class="blog_form_label_div">
        <label for="blog_description">Description</label>
      </div>
      <div class="blog_form_input_div">
        <textarea class="form-control" name="blog_description" id="blog_description"
          placeholder="optional (takes word doc 2nd/3rd paragraph)" form="form_edit">{{ description }}</textarea>
      </div>


      <div class="blog_form_label_div">
        Date
      </div>
      <div class="blog_form_input_div">
        <input type="date" name="blog_date_published" class="form-control" value="{{ post_date }}" form="form_edit">
      </div>
      

      <div class="blog_form_label_div">
        time_stamp_utc
      </div>
      <div class="blog_form_input_div">
        <input type="date" name="blog_date_published" class="form-control gray_input" value="{{ post_time_stamp_utc }}" readonly>
      </div>



      <div class="blog_form_buttons">

        <div class="button_div_right">
          <input type="submit" value="Upload" class="btn btn-primary" form="form_edit">
        </div>

      </div><!-- blog_form_buttons -->
      
    </div><!-- blog_form_sub_top-->
  </div><!-- blog_form_div -->

</div><!-- edit_post_super -->


  {% endblock %}

app_package/templates/blog/index.html
{% extends "_layout.html" %}

{% block title %}Blog{% endblock %}

{% block main %}

<div class="space_for_navbar_and_footer">


<div class="post_index flex_center">

    <div class="grid5_blog ">
        <div class="std_framing">
          {% if current_user.is_authenticated %}
          <div class="div_link_to_rest">
            <a href="{{ url_for('bp_blog.blog_user_home') }}" > Blog User Home </a>
          </div>
          {% endif %}
            <div class="div_link_to_rest">
                <a href="{{ url_for('bp_main.home') }}" id="go_home_link"> Go Home</a>
              </div>


          <div class="grid5_blog_title_super">
            {% if current_user.admin %}
            <a href="{{ url_for('bp_blog.blog_user_home' ) }}" class="no_show">
              <div class="grid5_blog_title"><h2>Blog Posts</h2></div>
            </a>

            {% else %}
            <div class="grid5_blog_title"><h2>Blog Posts</h2></div>
            {% endif %}

          </div><!-- grid5_blog_title -->


          
          {% for post in blog_posts_list %}
        
          <div class="blogpost_super">

            <a href="{{ url_for('bp_blog.view_post', post_dir_name=post[3]) }}">

              <div class="blogpost">
                <div class="blogpost_date">
                  {{ post[0] }}
                </div>

                <div class="blogpost_title">
                  {{ post.1 }}
                </div>


                <div class="blogpost_description">
                  {{ post.2 }}
                </div>

              </div><!-- blogpost -->
            </a>
          </div><!-- blogpost_super -->


          {% endfor %}


        </div><!-- std_framing -->

      </div><!-- grid5_blog -->


</div><!-- post_index -->
</div><!-- space_for_navbar_and_footer -->
{% endblock %}

app_package/templates/blog/user_home.html
{% extends "_layout.html" %}
{% block title %} User Blog Home {% endblock %}
{% block main %}
<form method="POST" id="form_user_home" enctype=multipart/form-data></form>

<div class="space_for_navbar_and_footer">


  <div class="blog_home_super">

    <div class="blog_home">

      <h2>Dashboards and Databases Blog Posts</h2>

      <div class="post_btn_div">
        <a class="btn btn-info extra_padding" href="{{ url_for('bp_blog.create_post') }}">Create Post</a>

      </div><!-- post_btn_div -->
      <div class="admin_btn_div">

        <a href="{{ url_for('bp_admin.admin_page' ) }}" class="btn btn-info">Admin Database</a>
      </div><!-- admin_btn_div -->


      <div class="table_background_sub">
        <div class="table_background">
          <table id="table_id" class="display table responsive ">
            <thead>
              <tr>
                {% for i in column_names %}
                <th>{{ i }}</th>
                {% endfor %}

              </tr>
            </thead>
            <tbody>
              {% for row in posts_details_list %}
              <tr>
                <td><!-- post Id-->
                  {{ row[0] }}
                </td>

                <td><!-- blog title -->
                  <div class="td_characteristics">

                    {{ row[1] }}
                  </div>
                </td>

                <td><!-- delete -->
                  <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#deleteModal"
                    data-bs-whatever="{{ row[0] }}">Delete</button>
                </td>

                {% for i in range(2,len(row)-1) %}
                <td>
                  <div class="td_characteristics">
                    {{ row[i] }}
                  </div>
                </td>
                {% endfor %}

                <td>
                  <a href="{{ url_for('bp_blog.blog_edit', post_id= row[0] ) }}" class="btn btn-info">{{ row[4] }}</a>

                </td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
        </div><!-- table_background -->
      </div><!-- table_background_sub -->

      <!-- Modal Delete -->
      <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        {% include "modals/delete_post.html" %}
      </div><!-- modal -->
    </div><!-- blog_home -->



  </div><!-- blog_home_super -->
</div><!-- space_for_navbar_and_footer -->






<script type="text/javascript">
$(document).ready(function () {
  $('#table_id').DataTable();
});
</script>



<!--Delete modal read record id-->
<script>
  var deleteModal = document.getElementById('deleteModal')
  deleteModal.addEventListener('show.bs.modal', function (event) {
    // Button that triggered the modal
    var button = event.relatedTarget
    // Extract info from data-bs-* attributes
    var recipient = button.getAttribute('data-bs-whatever')
    // If necessary, you could initiate an AJAX request here
    // and then do the updating in a callback.
    //
    // Update the modal's content.
    var modalTitle = deleteModal.querySelector('.modal-title')
    var modalBodyInput = deleteModal.querySelector('.modal-body input')

    modalTitle.textContent = 'Delete record ' + recipient + '?'
    modalBodyInput.value = recipient

  });
</script>


{% endblock %}

app_package/templates/blog/view_post.html
{% extends "_layout.html" %}
{% block main %}
<div class="space_for_navbar_and_footer">



<div class="view_post_super">

    <div class="view_post">


        {% if current_user.is_authenticated %}
        <div class="div_right">
          <a href="{{ url_for('bp_blog.blog_user_home') }}" > Blog User Home </a>
        </div>
        {% endif %}
        <div class="post">
          {% include template_post_index %}
        </div>
        
    </div>
    
</div><!-- view_post_super -->

</div><!-- space_for_navbar_and_footer -->


{% endblock %}