app_package/bp_main/routes.py
from flask import Blueprint
from flask import render_template, current_app, send_from_directory, g, \
    request
import os
from app_package._common.utilities import custom_logger, wrap_up_session
from ws_utilities import create_df_from_db_table_name
from ws_models import DatabaseSession

logger_bp_main = custom_logger('bp_main.log')
bp_main = Blueprint('bp_main', __name__)

# @bp_main.before_request
# def before_request():

#     # Assign a new session to a global `g` object, accessible during the whole request
#     g.db_session = DatabaseSession()


#     if request.referrer:
#         logger_bp_main.info(f"- request.referrer: {request.referrer} ")
    
#     logger_bp_main.info(f"- db_session ID: {id(g.db_session)} ")
    
#     if request.endpoint:
#         logger_bp_main.info(f"- request.endpoint: {request.endpoint} ")

# @bp_main.after_request
# def after_request(response):
#     logger_bp_main.info(f"---- after_request --- ")
#     if hasattr(g, 'db_session'):
#         wrap_up_session(logger_bp_main, g.db_session)
#     return response

@bp_main.route("/", methods=["GET","POST"])
def home():
    logger_bp_main.info(f"-- in home page route --")
    # df_users = create_df_from_db_table_name('users')
    # logger_bp_main.info(df_users)

    return render_template('main/home.html')

@bp_main.route("/download_ios", methods=["GET","POST"])
def download_ios():
    logger_bp_main.info(f"-- in download_ios route --")
    # download_test_flight_link = "https://testflight.apple.com/join/ZXNq4c8s"
    # try:
    with open(os.path.join(current_app.config.get('WEBSITE_FILES'),'TestFlightUrl.txt'), 'r') as file:
        download_test_flight_link = file.read().strip()  # .strip() removes any leading/trailing whitespace
    
    # except:
    #     download_test_flight_link="https://testflight.apple.com/join/LHzvgt5g"

    return render_template('main/download_ios.html', download_test_flight_link=download_test_flight_link)

@bp_main.route("/about", methods=["GET","POST"])
def about():
    logger_bp_main.info(f"-- in about page route --")

    test_flight_link = ""

    try:
        with open(os.path.join(current_app.config.get('WEBSITE_FILES'),'TestFlightUrl.txt'), 'r') as file:
            test_flight_link = file.read().strip()  # .strip() removes any leading/trailing whitespace
    except FileNotFoundError:
        logger_bp_main.info(f"- no TestFlight Link found")

    return render_template('main/about.html', test_flight_link=test_flight_link)

@bp_main.route('/privacy', methods = ['GET', 'POST'])
def privacy():
    logger_bp_main.info(f"-- in privacy page route --")
    return render_template('main/privacy.html')

@bp_main.route('/user_csv_documentation', methods = ['GET', 'POST'])
def user_csv_documentation():
    logger_bp_main.info(f"-- in user_csv_documentation route --")
    return render_template('main/user_csv_documentation.html')

@bp_main.route('/what_sticks_video/<filename>', methods = ['GET', 'POST'])
def what_sticks_video(filename):
    logger_bp_main.info(f"-- in what_sticks_video route --")

    if filename == "SleepTime20240130_shortDrawings.mp4":
        filename = "SleepTime_v03.mp4"

    return render_template('main/video_page.html', filename=filename)

# Website Files static data
@bp_main.route('/website_images/<filename>')
def website_images(filename):
    print("-- entered website_images -")
    print(f"Path to image file: {current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES')}")
    print(f"image filename: {filename}")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'), filename)

# Website Videos static data
@bp_main.route('/website_videos/<filename>')
def website_videos(filename):
    print("-- entered website_videos -")
    print(f"Path to image file: {current_app.config.get('DIR_WEBSITE_VIDEOS')}")
    print(f"image filename: {filename}")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_VIDEOS'), filename)

@bp_main.route('/website_images_favicon/<filename>')
def website_images_favicon(filename):
    print("-- entered website_images -")
    print(f"Path to image file: {os.path.join(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),'Favicon')}")
    print(f"image filename: {filename}")
    return send_from_directory(os.path.join(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),"Favicon"), filename)

@bp_main.route('/favicon_ico')
def favicon_ico():
    print("--- ** Favicon() ** ----")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),
                               'Favicon/favicon.ico', mimetype='image/vnd.microsoft.icon')

@bp_main.route('/robots.txt')
def robots_txt():
    # return send_from_directory(app.static_folder, 'robots.txt')
    return send_from_directory(current_app.config.get('WEBSITE_FILES'), 'robots.txt')

app_package/templates/main/about.html
{% extends "_layout.html" %}
{% block main %}
<!-- <div class="main_super"> -->

    <div class="about_page">

        <div class="col_1">

            <div class="col_1_sub">
                <div class="title_custom">
                    <h1>What Sticks</h1>
                    <div id="small_screen_logo">
                        <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}"/>
                    </div>
                </div>

                <div class="std_frame_light_gray std_frame_download">
                    <div class="std_frame_sub">
                        <h3>Goal and Mission</h3>
                        Give users agency over their health data so they can reap the benefits from their own data.
                        <ul>
                            <li>Making your data accessible</li>
                            <li>Making your data useful</li>
                        </ul>
                        
                    </div>
                </div><!-- std_frame_light_gray -->

                <div class="std_frame_light_gray std_frame_download">
                    <div class="std_frame_sub">
                        <h3>More to digest</h3>
                        
                        <ul>
                            <li><i class="date_font">2024-06-03</i>: The What Sticks problem statement <a href="{{ url_for('bp_main.what_sticks_video', filename='wsProblemStatement16.mp4') }}">video here</a>.<span class="font_highlight">New!</span></li> 
                            <li><i class="date_font">2024-05-19</i>: Location tracking feature (iOS 2.1 release) <a href="{{ url_for('bp_main.what_sticks_video', filename='WsLocationFeature_v02.mp4') }}">video here</a>.</li> 
                            <li><i class="date_font">2024-02-01</i>: App launch <a href="{{ url_for('bp_main.what_sticks_video', filename='LaunchVideo_v02.mp4') }}">video here</a>.</li>
                            <li><i class="date_font">2024-01-30</i>: <a href="{{ url_for('bp_main.what_sticks_video', filename='SleepTime_v03.mp4') }}">Video</a> of iOS app you can download now.</li>
                            <li><i class="date_font">2022-11-20</i>: <a href="https://nick-rodriguez.info/what_sticks_video01">Video</a> of concept from 2022 prototype 
                                watch here</li>
                            <li><i class="date_font">2022-10-16</i>: <a href="https://medium.com/@nrodrig1/average-outside-temperature-has-no-impact-on-my-sleep-ce21ee7012c6">Article</a> 
                                using What Sticks data collection to provide insight on how temperature impacts my sleep. </li>
                            <li><i class="date_font">2021-10-25</i>: <a href="https://medium.com/@nrodrig1/healthcare-is-not-up-to-date-2e58c01c1477">Article</a> on advent of data in health in wellness </li>
                        </ul>
                    </div>
                </div><!-- std_frame_light_gray -->
                {% if test_flight_link[:8] == 'https://' %}
                <div class="std_frame_light_gray std_frame_download">
                    <div class="std_frame_sub">
                        <h3>Latest Beta Version</h3>
                        <div class="element_padding">
                            <a href="{{ url_for('bp_main.download_ios') }}"><i class="fa-solid fa-download"></i>Download iOS</a>
                        </div>
                        
                    </div>
                </div><!-- std_frame_light_gray -->
                {% endif %}

                <div class="std_frame_light_gray std_frame_download">
                    <div class="std_frame_sub">
                        Contact Us: nrodrig1@gmail.com
                    </div>
                </div><!-- std_frame_light_gray -->


                <div class="excess_space"></div>

            </div><!-- col_1_sub -->
        </div><!-- col_1 -->
    </div><!-- home_page -->
<!-- </div>main_super -->



{% endblock %}

app_package/templates/main/download_ios.html
{% extends "_layout.html" %}
{% block main %}
<div class="main_super">

    <div class="download_ios_page">

        <div class="col_1">

            <div class="col_1_sub">
                <div class="title_custom">
                    <h1>What Sticks</h1>
                    <div id="small_screen_logo">
                        <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}"/>
                    </div>
                </div>

                <div class="std_frame_light_gray std_frame_download">
                    <div class="std_frame_sub">
                        <div class="std_frame_sub_col_1_main_text">Download Apple <i>TestFlight</i> and start using What Sticks.</div>
                    </div>
                </div><!-- std_frame_light_gray -->

                <div class="std_frame_light_gray std_frame_download">
                    <div class="std_frame_sub step_1_div_for_big">
                        Step 1: Go to download page click 
                        <a  href="{{ download_test_flight_link }}" target="_blank">{{ download_test_flight_link }}</a>
                    </div>
                    <div class="std_frame_sub step_1_div_for_small">
                        Step 1: Go to download page click <a href="{{ download_test_flight_link }}" target="_blank">here</a>
                    </div>
                </div><!-- std_frame_light_gray -->

                <div class="std_frame_light_gray std_frame_download_taller ">
                    <div class="std_frame_sub_2_columns">
                        <div class="std_frame_sub_col_1">
                            <div class="std_frame_sub_col_1_main_text">
                                Step 2: Download TestFlight 
                            </div>
                            
                            <div class="std_frame_sub_col_1_small_text">
                                TestFlight is an Apple Application that allows testing of new applicaitons.
                            </div>
                            
                        </div>
                        <div class="std_frame_sub_col_2">
                                <a href="#DownloadTestFlight">
                                    <img class="img_screen_shot" 
                                    src="{{ url_for('bp_main.website_images', filename='DownloadTestFlight_arrow.PNG') }}"/>
                                </a>
                        </div>
                    </div><!-- std_frame_sub_2_columns -->
                </div><!-- std_frame_light_gray std_frame_download_taller -->

                <div class="std_frame_light_gray std_frame_download_taller">
                    <div class="std_frame_sub_2_columns">
                        <div class="std_frame_sub_col_1">Step 3: In TestFlight select the latest What Sticks</div>
                        <div class="std_frame_sub_col_2">
                            <a href="#DownloadWhatSticks">
                                <img class="img_screen_shot" 
                                src="{{ url_for('bp_main.website_images', filename='DownloadWhatSticks_v03_arrow.jpeg') }}"/>
                            </a>
                        </div>
                    </div><!-- std_frame_sub_2_columns -->
                </div><!-- std_frame_light_gray std_frame_download_taller -->

                <div class="std_frame_light_gray std_frame_download">
                    <div class="std_frame_sub_register_login">
                        <div class="std_frame_sub_col_1 std_frame_sub_col_1_center_text"><h3>Register and login!</h3></div>
                    </div><!-- std_frame_sub_2_columns -->
                </div><!-- std_frame_light_gray std_frame_download_taller -->
                
                <div class="std_frame_last_on_page"></div>

            </div><!-- col_1_sub -->
        </div><!-- col_1 -->

        <div id="DownloadTestFlight" class="lightbox">
            <a href="#">
                <img class="img_screen_shot" 
                src="{{ url_for('bp_main.website_images', filename='DownloadTestFlight_arrow.PNG') }}"/>
            </a>
        </div><!-- lightbox: DownloadTestFlight -->

        <div id="DownloadWhatSticks" class="lightbox">
            <a href="#">
                <img class="img_screen_shot" 
                src="{{ url_for('bp_main.website_images', filename='DownloadWhatSticks_v03_arrow.jpeg') }}"/>
            </a>
        </div><!-- lightbox: DownloadWhatSticks -->
    </div><!-- home_page -->
</div><!-- main_super -->



{% endblock %}

<script>
    // Optional: JavaScript to handle closing the lightbox by clicking anywhere
    document.querySelectorAll('.lightbox').forEach(lightbox => {
        lightbox.onclick = function() {
            window.location.hash = '';
        };
    });
</script>

app_package/templates/main/home.html
{% extends "_layout.html" %}
{% block main %}
<!-- <div class="main_super"> -->

    <div class="home_page">

        <div class="col_1">
            <!-- <div class="col_1_sub"> -->
                <div class="title_custom">
                    <h1>What Sticks</h1>
                        <div id="small_screen_logo">
                            <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}"/>
                        </div>
                </div>

                <div class="std_frame_light_gray std_frame_fixed_size flex_center_vertically">
                    <div class="paragraph_home">
                        The application that provides insights on sleep and exercise based on data already collected by your devices.
                    </div>
                </div><!-- std_frame_light_gray -->

                <div class="std_frame_light_gray std_frame_fixed_size flex_center_vertically">
                    <div class="paragraph_home download_ios">
                        <a href="https://apps.apple.com/us/app/what-sticks-12/id6498888495">Download iOS</a>
                    </div>
                </div><!-- std_frame_light_gray -->

                <div class="execess_space"></div>

            <!-- </div>col_1_sub -->
        </div><!-- col_1 -->

    
    </div><!-- home_page -->
<!-- </div>main_super -->
{% endblock %}

app_package/templates/main/privacy.html
{% extends "_layout.html" %}
{% block main %}
<!-- <div class="main_super"> -->

<div class="privacy_page">

    <div class="col_1">
        <!-- <div class="col_1_sub"> -->
        <div class="title_custom">
            <h1>What Sticks Privacy Policy</h1>
            <div id="small_screen_logo">
                <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}" />
            </div>
        </div>

        <div class="std_frame_light_gray std_frame_fixed_size flex_center_vertically">
            <div class="">
                Last Updated: 29 January 2024
            </div>
        </div><!-- std_frame_light_gray -->

        <div class="paragraph_privacy">
            Welcome to What Sticks! We are committed to pioneering modernized wellness solutions while rigorously
            protecting your privacy. This Privacy Policy explains how we collect, use, and share information through our
            What Sticks Platform (the "Platform").
        </div><!-- paragraph_privacy -->

        <div class="paragraph_privacy">
            <h3>1. Information Collection</h3>
            When you use our Platform, we collect the following types of information:
            <ul>
                <li>Personal Information: We collect personal information that you provide to us, such as your email
                    address, when you register for an account.</li>
                <li>Usage Data: We collect information about your interactions with our Platform, like the features you
                    use and the time, frequency, and duration of your activities.</li>
                <li>Wellness Information: We collect information approved by the user such as steps counts, heart rates, workout durations, etc.,</li>
            </ul>
        </div><!-- paragraph_privacy -->


        <div class="paragraph_privacy">
            <h3>2. Use of Information</h3>
            We use your information for the following purposes:
            <ul>
                <li>To provide, maintain, and improve our Platform and services.</li>
                <li>To personalize your experience.</li>
                <li>For benchmarking purposes, where your data is aggregated with other users' data to help you
                    understand your wellness journey in comparison to broader trends.</li>
                <li>For research and development purposes, always in aggregate and anonymized form.</li>
            </ul>
        </div><!-- paragraph_privacy -->

        <div class="paragraph_privacy">
            <h3>3. Data Sharing and Disclosure</h3>
            <ul>
                <li><b>Aggregate Information</b>: We may share aggregated and anonymized information with users or
                    research teams interested in wellness trends. This data will never contain your email or personally
                    identifiable information.</li>
                <li><b>Evaluation of Data Requests</b>: If there are requests for the anonymous, aggregated data, the
                    What Sticks team will evaluate these requests and may share the data without user emails or any
                    personally identifiable information.</li>
                <li><b>Legal Requirements</b>: We may disclose your information if required by law or if we believe that
                    the disclosure is necessary to protect our rights and/or comply with a judicial proceeding, court
                    order, or legal process.</li>
            </ul>
        </div><!-- paragraph_privacy -->

        <div class="paragraph_privacy">
            <h3>4. Data Storage and Security</h3>
            Your information is securely stored on What Sticks Servers. We employ a variety of security measures to
            maintain the safety of your personal information.
        </div><!-- paragraph_privacy -->

        <div class="paragraph_privacy">
            <h3>5. Changes to this Privacy Policy</h3>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
        </div><!-- paragraph_privacy -->

        <div class="paragraph_privacy">
            <h3>6. Contact Us</h3>
            If you have any questions about this Privacy Policy, please contact us at nrodrig1@gmail.com.
        </div><!-- paragraph_privacy -->



        <div class="execess_space"></div>

        <!-- </div>col_1_sub -->
    </div><!-- col_1 -->


</div><!-- home_page -->
<!-- </div>main_super -->
{% endblock %}

app_package/templates/main/user_csv_documentation.html
{% extends "_layout.html" %}
{% block main %}
<!-- <div class="main_super"> -->

<div class="user_documentation_page">

    <div class="col_1">
        <!-- <div class="col_1_sub"> -->
        <div class="title_custom">
            <h1>What Sticks User CSV file Description</h1>
            <div id="small_screen_logo">
                <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}" />
            </div>
        </div>

        <div class="std_frame_light_gray std_frame_fixed_size flex_center_vertically">
            <div class="">
                Last Updated: 6 June 2024
            </div>
        </div><!-- std_frame_light_gray -->



        <h2 >Addressing sleep</h2>
        <p class="paragraph_doc" >The
        key here is sleep traverse days. There are two ways we measure it.</p>

        <p class="paragraph_doc">First
        (<b>sleep dependent)</b>, if we believe sleep is affected by
        something we did during a day. We call this <i>sleep dependent</i>.
        We can take the start time of any recorded sleep as the date, unless
        it is the following day before 3pm. We are assuming 3pm as the latest
        cut off where this sleeping in.</p>

        <p class="paragraph_doc">Secondly
        (<b>sleep independent</b>), if we believe other factors are the
        result of sleep we take the sleep dependent date and subtract one
        date so that the date is now n-1 and occurring before the factor we
        believe to be depended on sleep.</p>

        {% if current_user.admin_permission %}
        <div class="admin_section">

        
        <h1 class="western">Key functions to produce daily metrics (admin only)</h1>
        <p class="paragraph_doc">get_startDate_dateOnly_sleep_adj()
        </p>
        <p class="paragraph_doc">If
        the user’s sleep time is prior to 3pm it count for the previous
        day.</p>
        <p class="paragraph_doc">If
        get_startDate_dateOnly_sleep_adj() is used then date values are changed to prior
        date</p>

        <h2 class="western">create_df_daily_sleep(df)
        </h2>
        <p class="paragraph_doc">When
        this is used we are calculating a correlation that assumes <b>sleep
        dependent</b>.</p>
        <p class="paragraph_doc">This
        function uses the user’s qty_cat_df and adjusts dates for sleep so
        that any sleep time before 3pm is considered the previous night’s
        sleep.</p>

        <p class="paragraph_doc">This
        allows for the sleep date to reflect sleep that happens that night.
        In other words, any metrics for running, heart rate, temperature are
        all occurring during or <i><u><b>before</b></u></i> the sleep that is
        recorded in that date.</p>

        <h2 class="western">create_df_n_minus1_daily_sleep(user_id, df_daily_sleep)</h2>
        <p class="paragraph_doc">When
        this is used we are calculating a correlation that assumes <b>sleep
        independent</b>. This function uses the output of  create_df_daily_sleep(df)
        and further subtracts one day in order to make the sleep date reflect
        the night before’s sleep. In other words, any metrics for running,
        heart rate, temperature are all occurring <i><u><b>after</b></u></i>
        or before the sleep that is recorded in that date.</p>
        </div>  
        {% endif %}  

        <h1 class="western">Files on a user’s page (Sleep Dependent
        Variable)</h1>
        <p class="paragraph_doc">All files from this section are result of
        ws_analysis/correlations_dfs/dep_var_sleep.py file.</p>
        <h2 class="western">sleep_steps</h2>
        <p class="paragraph_doc">Actual
        file name: user_{user_id:04}_df_daily_sleep_steps.csv</p>
        <p class="paragraph_doc">Sleep
        type: sleep dependent (sleep time dates are result of create_df_daily_sleep(df))</p>
        <p class="paragraph_doc">This
        output assumes the steps impact sleep.</p>
        <h2 class="western">sleep_heart_rate</h2>
        <p class="paragraph_doc">Actual
        file name: user_{user_id:04}_df_daily_sleep_heart_rate.csv</p>
        <p class="paragraph_doc">Sleep
        type: sleep dependent (sleep time dates are result of create_df_daily_sleep(df))</p>
        <p class="paragraph_doc">This
        output assumes the heart rate impact sleep.</p>
        <h2 class="western">sleep_workout_duration</h2>
        <p class="paragraph_doc">Actual
        file name: user_{user_id:04}_df_daily_sleep_workout_duration.csv</p>
        <p class="paragraph_doc">corr_sleep_workouts(df_qty_cat,
        df_workouts)</p>
        <p class="paragraph_doc">Sleep
        type: sleep dependent (sleep time dates are result of create_df_daily_sleep(df))</p>
        <p class="paragraph_doc">This
        output assumes the workout duration impacts sleep.</p>
        <h2 class="western">sleep_time_cloudcover</h2>
        <p class="paragraph_doc">Actual
        file name: user_{user_id:04}_df_daily_sleep_time_cloudcover.csv</p>
        <p class="paragraph_doc">Sleep
        type: sleep dependent (sleep time dates are result of create_df_daily_sleep(df))</p>
        <p class="paragraph_doc">This
        output assumes the cloud cover impacts sleep.</p>

        <h2 class="western">sleep_time_temperature</h2>
        <p class="paragraph_doc">Actual
        file name: user_{user_id:04}_df_daily_sleep_time_temperature.csv</p>
        <p class="paragraph_doc">Sleep
        type: sleep dependent (sleep time dates are result of create_df_daily_sleep(df))</p>
        <p class="paragraph_doc">This
        output assumes the temperature impacts sleep.</p>
        <h1 class="western">Files on a user’s page (Sleep Independent
        Variable)</h1>
        <p class="paragraph_doc">All files from this section are result of
        dep_var_steps.py</p>
        <h2 class="western">steps_sleep</h2>
        <p class="paragraph_doc">Actual
        file name: user_{user_id:04}_df_daily_steps_sleep.csv</p>
        <p class="paragraph_doc">Sleep
        type: sleep independent (sleep time dates are result of create_df_n_minus1_daily_sleep(user_id, df_daily_sleep)).</p>
        <p class="paragraph_doc">This
        output assumes sleep impacts step counts the next day.</p>

        <h2 class="western">steps_heart_rate_n_minus1</h2>
        <p class="paragraph_doc">Actual
        file name: user_{user_id:04}_df_daily_steps_heart_rate_n_minus1.csv</p>
        <p class="paragraph_doc">heart
        rate type: heart rate independent heart rate uses the
        <i>create_df_n_minus1_daily_heart_rate(df_daily_heart_rate)</i>
        function to subtract a day from the heart rate date. This output
        assumes heart rate impacts step counts of the next day.</p>


        <div class="execess_space"></div>

        <!-- </div>col_1_sub -->
    </div><!-- col_1 -->


</div><!-- home_page -->
<!-- </div>main_super -->
{% endblock %}

app_package/templates/main/video_page.html
{% extends "_layout.html" %}
{% block main %}

<!-- <div class="main_super"> -->

    <div class="video_page">
        <div class="col_1">
            {% if filename == "SleepTime20240130_shortDrawings.mp4" %}
            <!-- Only keep this while waiting on Apple App Store Response -->
            <div class="video-container">
                <video controls>                   
                    <source src="{{ url_for('bp_main.website_videos', filename='SleepTime_v03.mp4')}}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
            {% else %}
            <div class="video-container">
                <video controls>                   
                    <source src="{{ url_for('bp_main.website_videos', filename=filename)}}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
            {% endif %}

        </div><!-- col_1 -->
    </div><!-- video_page -->
<!-- </div>main_super -->

{% endblock %}