app_package/bp_main/routes.py
from flask import Blueprint
from flask import render_template, current_app, send_from_directory, g, \
    request
import os
from app_package._common.utilities import custom_logger, wrap_up_session
from ws_utilities import create_df_from_db_table_name
from ws_models import DatabaseSession

logger_bp_main = custom_logger('bp_main.log')
bp_main = Blueprint('bp_main', __name__)

# @bp_main.before_request
# def before_request():

#     # Assign a new session to a global `g` object, accessible during the whole request
#     g.db_session = DatabaseSession()


#     if request.referrer:
#         logger_bp_main.info(f"- request.referrer: {request.referrer} ")
    
#     logger_bp_main.info(f"- db_session ID: {id(g.db_session)} ")
    
#     if request.endpoint:
#         logger_bp_main.info(f"- request.endpoint: {request.endpoint} ")

# @bp_main.after_request
# def after_request(response):
#     logger_bp_main.info(f"---- after_request --- ")
#     if hasattr(g, 'db_session'):
#         wrap_up_session(logger_bp_main, g.db_session)
#     return response

@bp_main.route("/", methods=["GET","POST"])
def home():
    logger_bp_main.info(f"-- in home page route --")
    # df_users = create_df_from_db_table_name('users')
    # logger_bp_main.info(df_users)

    return render_template('main/home.html')

@bp_main.route("/download_ios", methods=["GET","POST"])
def download_ios():
    logger_bp_main.info(f"-- in download_ios route --")
    # download_test_flight_link = "https://testflight.apple.com/join/ZXNq4c8s"
    # try:
    with open(os.path.join(current_app.config.get('WEBSITE_FILES'),'TestFlightUrl.txt'), 'r') as file:
        download_test_flight_link = file.read().strip()  # .strip() removes any leading/trailing whitespace
    
    # except:
    #     download_test_flight_link="https://testflight.apple.com/join/LHzvgt5g"

    return render_template('main/download_ios.html', download_test_flight_link=download_test_flight_link)

@bp_main.route("/about", methods=["GET","POST"])
def about():
    logger_bp_main.info(f"-- in about page route --")

    test_flight_link = ""

    try:
        with open(os.path.join(current_app.config.get('WEBSITE_FILES'),'TestFlightUrl.txt'), 'r') as file:
            test_flight_link = file.read().strip()  # .strip() removes any leading/trailing whitespace
    except FileNotFoundError:
        logger_bp_main.info(f"- no TestFlight Link found")

    return render_template('main/about.html', test_flight_link=test_flight_link)

@bp_main.route('/privacy', methods = ['GET', 'POST'])
def privacy():
    logger_bp_main.info(f"-- in privacy page route --")
    return render_template('main/privacy.html')

@bp_main.route('/user_csv_documentation', methods = ['GET', 'POST'])
def user_csv_documentation():
    logger_bp_main.info(f"-- in user_csv_documentation route --")
    return render_template('main/user_csv_documentation.html')

@bp_main.route('/what_sticks_video/<filename>', methods = ['GET', 'POST'])
def what_sticks_video(filename):
    logger_bp_main.info(f"-- in what_sticks_video route --")

    if filename == "SleepTime20240130_shortDrawings.mp4":
        filename = "SleepTime_v03.mp4"

    return render_template('main/video_page.html', filename=filename)

# Website Files static data
@bp_main.route('/website_images/<filename>')
def website_images(filename):
    print("-- entered website_images -")
    print(f"Path to image file: {current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES')}")
    print(f"image filename: {filename}")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'), filename)

# Website Videos static data
@bp_main.route('/website_videos/<filename>')
def website_videos(filename):
    print("-- entered website_videos -")
    print(f"Path to image file: {current_app.config.get('DIR_WEBSITE_VIDEOS')}")
    print(f"image filename: {filename}")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_VIDEOS'), filename)

@bp_main.route('/website_images_favicon/<filename>')
def website_images_favicon(filename):
    print("-- entered website_images -")
    print(f"Path to image file: {os.path.join(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),'Favicon')}")
    print(f"image filename: {filename}")
    return send_from_directory(os.path.join(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),"Favicon"), filename)

@bp_main.route('/favicon_ico')
def favicon_ico():
    print("--- ** Favicon() ** ----")
    return send_from_directory(current_app.config.get('DIR_WEBSITE_UTILITY_IMAGES'),
                               'Favicon/favicon.ico', mimetype='image/vnd.microsoft.icon')

@bp_main.route('/robots.txt')
def robots_txt():
    # return send_from_directory(app.static_folder, 'robots.txt')
    return send_from_directory(current_app.config.get('WEBSITE_FILES'), 'robots.txt')

app_package/templates/users/login.html
{% extends "_layout.html" %}
{% block main %}
<form method="POST" id="form_1"></form>

<!-- <div class="main"> -->
<!-- <div class="space_for_navbar_and_footer flex_center"> -->
<div class="login_page">

  <div class="col_1">

    <div class="title_custom">
      <h1>Login</h1>
      <div id="small_screen_logo">
        <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}" />
      </div>
    </div>


    <div class="login_form">

      <div class="login_form_sub">

        <div class="email_form">
          <label for="email">Email:</label>
          <input type="text" id="email" name="email" form="form_1">
        </div>

        <div class="password_form">
          <label for="password">Password:</label>
          <input type="password" id="password_text" name="password" form="form_1">
        </div>




        <div class="element_right">

          <div class="show_password">
            <input class="form-check-input" type="checkbox" value="" id="password_checkbox" form="form_1">
            <label class="form-check-label" for="password_checkbox">
              Show password
            </label>
          </div>


          <div class="element_right_sub">
            <input type="submit" value="Login" name="btn_login" class="btn btn-secondary btn_custom01" form="form_1">
            <!-- <input type="submit" value="Login As Guest" name="btn_login_as_guest" class="btn btn-secondary btn_custom02"> -->

            <div class="forgot_password">
              <a href="{{ url_for('bp_users.request_reset_password') }}">Forgot Password?</a>
            </div>
            <div class="not_registered">
              <!-- <a href="{ url_for('bp_users.register') ">Not registered?</a> -->
            </div>
          </div>

        </div>

      </div><!-- login_form_sub -->
    </div><!-- login_form -->


  </div>
</div><!-- main -->

<!-- Show password -->
<script>
  window.addEventListener("load", function () {
    var checkbox = document.getElementById('password_checkbox');
    var x = document.getElementById('password_text');
    checkbox.addEventListener('change', function () {
      if (this.checked) {
        x.type = 'text';
      } else {
        x.type = 'password';
      }
    });
  });
</script>

{% endblock %}

app_package/templates/users/register.html
{% extends "_layout.html" %}
{% block main %}


<div class="register_page">

  <div class="col_1">

    <div class="title_custom">
      <h1>Register</h1>
      <div id="small_screen_logo">
        <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}" />
      </div>
    </div>

    <div class="register_form">
      <form method="POST" id="form_1">
        <div class="register_form_sub">

          <div class="email_form_group">
            <label for="email">Email:</label>
            <input type="text" id="email" name="email" class="register_text" form="form_1">
          </div>

          <div class="password_form_group">
            <label for="password">Password:</label>
            <input type="password" id="password_text" name="password" class="register_text" form="form_1" required>
          </div>

          <div class="submit_form_group">
            <input class="form-check-input" type="checkbox" value="" id="password_checkbox" form="form_1">
            <label class="form-check-label" for="password_checkbox">
              Show password
            </label>
            <br>
            <div class="element_right">
              <input type="submit" value="Submit" class="btn btn-secondary btn_custom01" form="form_1">
            </div>
          </div>

        </div><!-- register_form_sub -->

      </form>


    </div><!-- register_form -->





  </div>
</div><!-- main -->

<!-- Show password -->
<script>
  window.addEventListener("load", function () {
    var checkbox = document.getElementById('password_checkbox');
    var x = document.getElementById('password_text');
    checkbox.addEventListener('change', function () {
      if (this.checked) {
        x.type = 'text';
      } else {
        x.type = 'password';
      }
    });
  });
</script>

{% endblock %}

app_package/templates/users/reset_request.html
{% extends "_layout.html" %}
{% block main %}
<form method="POST" id="form_1"></form>


<!-- <div class="main"> -->
<!-- <div class="space_for_navbar_and_footer flex_center"> -->
<div class="password_reset_page">

  <div class="col_1">

    <div class="title_custom">
      <h1>{{ page_name }}</h1>
      <div id="small_screen_logo">
        <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}" />
      </div>
    </div>



    <div class="std_frame_light_gray">
      <!-- <form method="POST" action=""> -->
        
        <div class="password_reset_sub">
          {% if token %}

          <div class="password_input">
            <label for="password">Password:</label>
            <input type="password" id="password_text" name="password_text" class="register_text" form="form_1">
          </div>


          {% else %}

          <div class="email_input">
            <label for="email">Email:</label>
            <input type="text" id="email" name="email" class="register_text" form="form_1">
          </div>

          {% endif %}
    
          <div class="bottom_element">
            {% if token %}
            <div class="password_checkbox">
              <input class="form-check-input" type="checkbox" value="" id="password_checkbox" form="form_1">
              <label class="form-check-label" for="password_checkbox">Show password</label>
            </div>


              <input type="submit" value="Update" class="btn btn-primary " form="form_1">
            {% else %}
            
              <input type="submit" value="Submit" class="btn btn-secondary btn_custom01" form="form_1">
            {% endif %}
            </div><!-- bottom_element -->
        </div><!-- password_reset_sub -->


      </div><!-- password_reset_form-->

      <!-- </form> -->


  </div><!-- col 1-->
</div><!-- password_reset_page -->


<!-- Show password -->
<script>
  window.addEventListener("load", function () {
    var checkbox = document.getElementById('password_checkbox');
    var x = document.getElementById('password_text');
    checkbox.addEventListener('change', function () {
      if (this.checked) {
        x.type = 'text';
      } else {
        x.type = 'password';
      }
    });
  });
</script>



{% endblock %}

app_package/templates/users/user_home.html
{% extends "_layout.html" %}
{% block main %}
<form method="POST" id="form_download_db" enctype=multipart/form-data></form>
<form method="POST" id="form_recalculate_dash" enctype=multipart/form-data></form>

<div class="user_home_page">

    <div class="col_1">

        <div class="title_custom">
            <h1>What Sticks</h1>
            <div id="small_screen_logo">
                <img class="img_logo" src="{{ url_for('bp_main.website_images', filename='wsLogo180noName.png') }}" />
            </div>
        </div>

        <div class="username">
            {{ current_user.username }} data files:
        </div>

        {% if len(user_files_list) > 0 %}
        <div class="paragraph_user_home">
            <ul>
                {% for csv_filename, csv_filename_short in zip(user_files_list, user_files_list_shortname) %}
                <li><a href="{{ url_for('bp_users.user_file', filename= csv_filename )}}">{{ csv_filename_short }}</a></li>
                {% endfor %}
                <li><hr></li>
                <li><a href="{{ url_for('bp_main.user_csv_documentation') }}"><i class="fa-regular fa-file"></i><span> CSV file documentation</span></a></li>
            </ul>
        </div><!-- paragraph_privacy -->
        <div class="hr_for_user_home">
            <hr>
        </div>

        <div class="std_frame_light_gray">
            <div class="">
                These files represent the data used to calculate your latest dashboard correlations.
                <div class="element_to_right">
                    <button type="submit" name="btn_download_files" value="zip_file" class="btn btn-primary"
                    form="form_download_db">Download Zip</button>
                </div>
            </div>
        </div><!-- std_frame_light_gray -->


        {% else %}
        <div class="paragraph_user_home">You have not uploaded any data.</div>
        {% endif %}

        <div class="std_frame_light_gray">
            <div class="">
                Recalculate your iPhone dashboard.
                <br>
                <p class="gray-font">
                The primary reason for this is if you think you have added new data and the calculations on your iPhone are not consistent with your new data.
                Recalculating will redo the calculations that show up on your iPhone app. 
                Also, if there are changes the will reflect in the data files on this page.
                </p>
                <div class="element_to_right">
                    <button type="submit" name="btn_recalculate_dashboard" value="dashboard" class="btn btn-primary"
                    form="form_recalculate_dash">Recalculate Dashboard</button>
                </div>
            </div>
        </div><!-- std_frame_light_gray -->

        <div class="execess_space"></div>

    </div><!-- col_1 -->


</div><!-- user_home_page -->

{% endblock %}